# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='seen',
            new_name='received',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
