# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='username',
        ),
    ]
